### ISSUE TITLE
DirPreparation 

### ISSUE THREAD

**Issue by quotentiroler** [quotentiroler/plagiarismchecker#1]
DirPreparation is there to convert a directory consisting of multiple repositories to a directory that this plagiarism check works with. 

It is not fully implemented yet. It still needs to process sub-dirs in the source folder. Also, it only considers files in the source folder which might not be the best approach.

**Comment by quotentiroler** [comment]
Idea: 
Instead of uploading files, it could be a thing to insert github repos URLs, walk through them and process all code files for document fingerprint creation.

**Comment by floatingdev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

Coinsag, @fuJiin, @lootstrum, @bluemix, @ulkaio, @skrizzles, @vaayne, @vperilla, @DarthMike, @lamida, @carmelosantana, @carlbarrdahl, @hyphen249, @Cyberdevil112, @LJ001, @zeroaiia, @WolfeCub, @minhtkh, @osantana, @brianjwoo
